// <auto-generated />
using DevelopersChallenge2Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevelopersChallenge2Api.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20190515052753_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("DevelopersChallenge2Api.Models.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcctId");

                    b.Property<double>("Amount");

                    b.Property<string>("BankId");

                    b.Property<string>("Currency");

                    b.Property<long>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "AcctId", "BankId")
                        .IsUnique();

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("DevelopersChallenge2Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcctId");

                    b.Property<double>("Amount");

                    b.Property<string>("BankId");

                    b.Property<string>("Currency");

                    b.Property<string>("Description");

                    b.Property<string>("OperationType");

                    b.Property<long>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Description", "Amount", "BankId", "AcctId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
